# services:
#   db:
#     image: postgres:16-alpine
#     container_name: shop-db
#     environment:
#       POSTGRES_USER: shop_user
#       POSTGRES_PASSWORD: shop_pass
#       POSTGRES_DB: shop_db
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U shop_user -d shop_db"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#   api:
#     build: .
#     container_name: shop-api
#     depends_on:
#       db:
#         condition: service_healthy
#     environment:
#       DB_URL: postgresql+psycopg2://shop_user:shop_pass@db:5432/shop_db
#       ENV: docker
#       LOG_LEVEL: INFO
#     ports:
#       - "8000:8000"

# volumes:
#   pgdata:






# version: "3.9"

# services:
#   db:
#     image: postgres:16
#     container_name: shop_db
#     restart: always
#     environment:
#       POSTGRES_USER: shop_user
#       POSTGRES_PASSWORD: shop_pass
#       POSTGRES_DB: shop_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - shop_data:/var/lib/postgresql/data

#   api:
#     build: .
#     container_name: shop_api
#     depends_on:
#       - db
#     env_file:
#       - .env        
#     ports:
#       - "8000:8000"
#     command: >
#       bash -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

# volumes:
#   shop_data:





services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_pass
      POSTGRES_DB: shop_db
    volumes:
      - shop_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["./entrypoint.sh"]

volumes:
  shop_data:
